### PR TITLE
fix add crudtrait to crud

### LINKED ISSUE #181: In L10 it fails adding CrudTrait
# Bug report

### What I did:

- installed a fresh Laravel 10 project
- installed Backpack on top
- tried to create the UserCRUD like instructed in the Getting Started widget

### What I expected to happen:

Everything to work.

### What happened:

Almost everything works. But the CrudTrait is not being added to the default `User` model:

CleanShot 2023-02-24 at 11 55 04

### What I've already tried to fix it:

Nothing yet. I assume it's because the User model now uses a bunch of traits, all on the same line?! We should account for that, ASAP.

### PR DESCRIPTION
**Pull request by pxpm**
fixes #181 

This is the same script snippet used in devtools `Add Crud Trait` button. 

We should probably extract this bit of code to some place where it could be re-used by both devtools button and generators command. 

For now they have the same code 👍

### CODE REVIEW

File: src/Console/Commands/CrudModelBackpackCommand.php [hunk 1]
```diff
@@ -101,45 +102,31 @@ public function handle()
...
             $this->progressBlock('Adding CrudTrait to the Model');
 
-            $file = $this->files->get($path);
-            $lines = preg_split('/(\r\n)|\r|\n/', $file);
+            $content = Str::of($this->files->get($path));
 
             // check if it already uses CrudTrait
             // if it does, do nothing
-            if (Str::contains($file, $this->crudTrait)) {
+            if (Str::contains($content, $this->crudTrait)) {
```
Comment (tabacitu) [inline src/Console/Commands/CrudModelBackpackCommand.php:109]: If we just created `$content` which is a `Str` object, that means we can use that `$content` object and fluent string helpers going forward, which are easier to read:

```suggestion
            if ($content->contains($this->crudTrait)) {
```

**Review by tabacitu — CHANGES_REQUESTED** [review]
I tested this but it doesn't seem like a complete solution:
- ✅ it adds `use Backpack\CRUD\app\Models\Traits\CrudTrait;` 
- ❌ it does NOT use it inside the class itself;

Back to the drawing board Pedro.

**Comment by tabacitu** [comment]
Also, I don't like that this adds an empty line after CrudTrait. Feels like we're introducing dirt to the model. Let's fix that. We can easily add the USE statement after "namespace + line break" then if that doesn't exist, add it after "namespace without line break".

**Comment by tabacitu** [comment]
Also... this just came to me. Why do we completely change how this is done?

If the problem we're trying to fix is "_when adding CrudTrait to User model, it adds to the commented line_"... why don't we check for that? If the line is commented, then add to the next line. Wouldn't that be simpler and keep all the benefits of the solution we had before?

**Comment by pxpm** [comment]
All of the above fixed. 👍

**Comment by tabacitu** [comment]
This still adds an empty line after the CrudTrait:
CleanShot 2023-02-28 at 18 20 25
